import Head from "next/head";
import Image from "next/image";
import Header from "@/components/Header";
import NavMenu from "@/components/NavMenu";
import Welcome from "@/components/Welcome";
import Overview from "@/components/Overview";
import requests from "@/utils/request";
// import axios from "axios";


import axios from "axios"
import { useQuery } from "react-query";



export default function Home() {
  const  {
    data:dashboardData
  } = useQuery(['dashboardDatas'], () => {
    return axios.get("https://dev.matadortrust.com/v2/developers/dashboard_data").then(({ data }) => data)
  })
  // const {data:dashboardData} = useQuery(() => getDashboardData())
  console.log(dashboardData,"my data index")
  // console.log(dashboardData, "lets see dashboard DAta")
  return (
    <>
      <div className="2xl:container 2xl:mx-auto">
        <Head>
          <title>Veerge For Mainstone</title>
          <meta name="description" content="Generated by create next app" />

          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <NavMenu />
        <Welcome />
        <Overview
        dashboardData = {dashboardData}
         />

        <main>
          <div className="text-red-400 font-semibold"></div>
        </main>
      </div>
    </>
  );
  
}

export const dashboard = async () => {
  const getDashboardData = await axios.get(requests.fetchDashboardData).then((res) => res.json())
}

// export const getServerSideProps = async () =>  {
//  const dashboardData = await  fetch(requests.fetchDashboardData).then((res) => res.json())
 




//  //return props in server side rendering
//  return {
//   props: {
//     dashboardData:dashboardData
    
    
//   },
// };
// }


