import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import NavMenu from "@/components/NavMenu";
import Welcome from "@/components/Welcome";

export default function Home() {
  return (
    <>
      <div className="relative h-screen">
        <Head>
          <title>Veerge For Mainstone</title>
          <meta name="description" content="Generated by create next app" />

          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <NavMenu />
        <Welcome />
        <main>
          <div className="text-red-400 font-semibold"></div>
        </main>
      </div>
    </>
  );
}
